logging:
  file: log/udp.log
  pattern:
    console: '[%clr(%p)] [%d{yyyy-MM-dd HH:mm:ss.sss}] [%t] %clr([%C.%M]%L:) %m%n'
    file: '[%p] [%d{yyyy-MM-dd HH:mm:ss.sss}] [%t] %C.%M %L %m%n'
  level:
    root: error
spring:
  application:
    name: server-ribbon
server:
  port: 8759
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#服务配置
zuul:
  routes:
    client:
      path: /client/**
      serviceId: client


