logging:
  file: log/udp.log
  pattern:
    console: '[%clr(%p)] [%d{yyyy-MM-dd HH:mm:ss.sss}] [%t] %clr([%C.%M]%L:) %m%n'
    file: '[%p] [%d{yyyy-MM-dd HH:mm:ss.sss}] [%t] %C.%M %L %m%n'
  level:
    root: error
spring:
  application:
    name: server-center
server:
  port: 8760
  servlet:
    session:
      timeout: 30m
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
#服务配置
#zuul:
#  routes:
#    client:
#      path: /client/**
#      serviceId: client
#信息



